### PR TITLE
Update entrypoint.sh

### PR DESCRIPTION
**Pull request by Bioblaze**
Without this change your system just doesn't work. 

`The Godot 3 --export option was changed to more explicit --export-release / --export-debug / --export-pack options.`

Is what it will say and just stop...

### CODE REVIEW

**Review by yeslayla — DISMISSED** [review]
Thanks for the fix!

**Comment by runik** [comment]
all our exports are broken now. is there temp workaround until this fix will be live in next version ?

**Comment by Bioblaze** [comment]
Give me a bit, i'm providing a fix.

**Comment by Bioblaze** [comment]
That should take care of it @yeslayla they made the folder names different then how they are stored, makes no sense to me but that should fix it now.

**Review by yeslayla — DISMISSED** [review]
I really appreciate the work and investigation here! ❤️

**Comment by Bioblaze** [comment]
Let me know if you want anything else. I'm debating on wither or not to add code-signing support too this package @.@ or make another package to be honest.

**Comment by yeslayla** [comment]
> Let me know if you want anything else. I'm debating on wither or not to add code-signing support too this package @.@ or make another package to be honest.

I've definitely not given it the love and support it has needed recently. I'm happy to grant contributor access. Or if you'd like to do some more substantial collaboration, I'm open to speaking privately. :)

**Comment by yeslayla** [comment]
Actually thinking about it, may be worth working towards a 2.0.

**Comment by Bioblaze** [comment]
hmm I agree @yeslayla what will 2.0 have in it? And I'll be glad to contribute since I'm using the repo :P

**Comment by Bioblaze** [comment]
Also add me on Discord: Bioblaze Payne#6459

**Comment by Bioblaze** [comment]
I think I figured out why it is not working, it is cause the project is 3 years old. :X updating with a new one and testing will tell yah if that fixes it shortly.

**Comment by Bioblaze** [comment]
OK @yeslayla everything is good now, Github Action Tests pass, also showcase support for Old Project, and New Project :p for 3.x and 4.x figured that was nice.

**Comment by knJayden** [comment]
Any chance we could get this merged and released?

**Review by alexissantos — APPROVED** [review]
@knJayden Reviewed -- should be good to go.

**Comment by yeslayla** [comment]
Apologies for the delays everyone. I'll get on trying to get some major improvements here soon.

Thanks again for the contribution @Bioblaze, I'll probably reach out here eventually :)

**Comment by Bioblaze** [comment]
kk if you got a discord Server @yeslayla I'll join it and we can chat. I'm using this in my CI/CD ;3

**Pull request merged**
